# Generated by Django 6.1.1 on 2026-09-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleetCard', '0002_veiculo_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('troca_oleo', 'Troca de óleo'), ('revisao', 'Revisão'), ('freios', 'Sistema de freios'), ('suspensao', 'Suspensão'), ('motor', 'Motor'), ('eletrica', 'Elétrica'), ('pneus', 'Pneus'), ('outros', 'Outros')], max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='FleetCard.veiculo')),
            ],
        ),
    ]
